/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

"use strict";

var obsidian = require("obsidian");

/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */

const DEFAULT_SETTINGS = {};

var highlighterColorsMap = [
    //This could be a flat object but idk
    { color: "Pink", value: "#FFB8EB" },
    { color: "Red", value: "#FF5582" },
    { color: "Orange", value: "#FFB86C" },
    { color: "Yellow", value: "#FFF3A3" },
    { color: "Green", value: "#BBFABB" },
    { color: "Blue", value: "#ADCCFF" },
    { color: "Purple", value: "#D2B3FF" },
    { color: "Grey", value: "#CACFD9" },
];

console.log("app:", app);

let newDiv = document.createElement("div");

if (newDiv) {
    var scope = document.querySelector("body");

    newDiv.setAttribute("id", "highlighterContainer");

    scope.addEventListener("contextmenu", (event) => {
        var clientHeight = 200;
        var clientWidth = 158;
        var { clientX: mouseX, clientY: mouseY } = event;

        newDiv.style.top = `${mouseY}px`;
        newDiv.style.left = `${mouseX}px`;

        if (clientHeight + mouseY > window.innerHeight) {
            newDiv.style.top = `${mouseY - clientHeight}px`;
        } else {
            newDiv.style.top = `${mouseY}px`;
        }

        if (clientWidth + mouseX > window.innerWidth) {
            newDiv.style.left = `${mouseX - clientWidth}px`;
        } else {
            newDiv.style.left = `${mouseX}px`;
        }

        console.log(
            clientHeight,
            mouseY,
            window.innerWidth,
            mouseX - clientWidth
        );
    });
}

class HighlightrPlugin extends obsidian.Plugin {}

module.exports = HighlightrPlugin;
